version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-construtora
    environment:
      MYSQL_DATABASE: construtora_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uadmin", "-padmin"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./construtora
    container_name: construtora-back
    environment:
      SERVER_PORT: 8092
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/construtora_db?createDatabaseIfNotExists=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
    ports:
      - "8092:8092"
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build: ./construtora-front
    container_name: construtora-front
    ports:
      - "3000:3000"
    volumes:
      - ./construtora-front:/app
    depends_on:
      - backend

volumes:
  mysql-data:
